import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout';
import Banner from '@/components/Home-Page/banner';
import ExploreByCategrory from '@/components/Home-Page/exploreByCategrory';
import FindTalent from '@/components/Home-Page/findTalent';
import FeaturedJobs from '@/components/Home-Page/featuredJobs';
import Freelance from '@/components/Home-Page/freelance';
import PostJob from '@/components/Home-Page/postJob';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Banner/>
      <ExploreByCategrory/>
      <FindTalent/>
      <FeaturedJobs/>
      <Freelance/>
      <PostJob/>
      </Layout>
    </>
  )
}



